name: open_fashion
description: "A new Flutter project."
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  go_router: ^14.1.4
  injectable: ^2.4.2
  get_it: ^7.7.0
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  freezed_annotation: ^2.4.1
  freezed: ^2.5.2
  hive: ^2.2.3
  path_provider: ^2.1.3
  path: ^1.9.0
  hive_flutter: ^1.1.0
  gap: ^3.0.1
  font_awesome_flutter: ^10.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  hive_generator: ^2.0.1


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/items/
    - assets/images/icons/

        
    
    
                                      